<!DOCTYPE html>
<html>
  <head>   
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
   <link rel="stylesheet" href="/CSS/main.css">
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" >

  </head>
  <body>
 
    {% block content %}{% endblock %}

<div class = "navbar navbar-default navbar-fixed-bottom">
  <div class = "container">
    <p class = "navbar-text pull-left">Built with love and confusion by Ian Castillo 2015</p>
      <div class="container">
      <div class="pull-right">
<a href="https://www.facebook.com/bootsnipp"><i id="social" class="fa fa-github-square fa-3x"></i></a>
<a href="https://twitter.com/bootsnipp"><i id="social" class="fa fa-twitter-square fa-3x"></i></a>
<a href="mailto:bootsnipp@gmail.com"><i id="social" class="fa fa-envelope-square fa-3x"></i></a>
      </div>
      </div>

  </div>
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"> </script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="/js/main.js"></script>
</body>
</html>