<!DOCTYPE html>
<html>
  <head>   
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
   <link rel="stylesheet" href="/CSS/main.css">
  </head>
  <body>
 
    {% block content %}{% endblock %}





    <div class = "navbar navbar-default navbar-fixed-bottom">
     <div class = "container">
      <p class = "navbar-text pull-left">Built with love and confusion by Ian Castillo 2015</p>
        <button type="button" class = "navbar-btn btn-danger btn pull-right">Maybe a Contact Button?</button>
        </button>
      </div>
    </div>
    </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"> </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="/js/main.js"></script>
  </body>
</html>